atSNPsearch/atSNPsearch/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^snpSearchTool/', include('snpSearchTool.urls')),
    url(r'^admin/', admin.site.urls),
]

atSNPsearch/snpSearchTool/urls.py
from django.conf.urls import url

from . import views

  #this is required to add another view?

app_name = 'snpSearchTool'
#include at least one example of a valid matching url for each of these.
urlpatterns = [
  #example: snpSearchTool/index
  #url(r'^$', views.index, name='index'),
  url(r'^$', views.IndexView.as_view(), name='index'),  

  #example :snpSearchTool/results/3
  url(r'^results/(?P<requested_snpid>[0-9]*)', views.results, name='results'),

  #example :snpSearchTool/3/detail
  #url(r'^(?P<id_of_scoresrow>[0-9]*)/detail', views.detail , name='detail'),
  #url(r'^(?P<id_of_requested_row>[0-9]*)/detail', views.detail , name='detail'),
  url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = 'detail'), 
 
  #example: snpSearchTool/controlset
  url(r'^controlset$', views.controlset, name='controlset'),

  url(r'^lookup_one_snp$', views.lookup_one_snp, name='lookup_one_snp'),
]

atSNPsearch/snpSearchTool/models.py
from __future__ import unicode_literals

from django.db import models

#human-readable names can be specified as first arguments to these:
class ScoresRow(models.Model):
  id = models.AutoField(primary_key=True)
  snpid = models.CharField(max_length=40)
  motif = models.CharField(max_length=20)
  motif_len = models.IntegerField(default=0)
  log_lik_ref = models.FloatField(default=0)
  log_lik_snp = models.FloatField (default=0)
  log_lik_ratio = models.FloatField (default=0)
  log_enhance_odds = models.FloatField (default=0)
  log_reduce_odds  = models.FloatField (default=0)
  ref_start = models.IntegerField(default=0)
  snp_start = models.IntegerField(default=0)
  ref_end = models.IntegerField(default=0)
  snp_end = models.IntegerField(default=0)
  ref_strand = models.CharField(max_length=1, default="")
  snp_strand = models.CharField(max_length=1, default="")
  #There should be some way to determine from the data in this model 
  #What transcription factors are involved for this row
  #eg: what's the threshold for each column to say that it's involved.
  class Meta:
    managed = False
    db_table = 'snp_scores_1'

  


  def __str__(self):
    return "One row of socres data for snp: " + self.snpid

class MessageClass(models.Model):
  message = models.CharField(max_length=200)
  
  def __str__(self):
    return "a message with message = " + message

#below this line, make a list of additional models to create
#class TranscriptionFactor(models.Model):

atSNPsearch/snpSearchTool/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import ScoresRow
from django.core.urlresolvers import reverse
from django.views import generic

#uses a generic view
class IndexView(generic.ListView):
  template_name = 'snpSearchTool/index.html'
  context_object_name = 'snp_list'

  def get_queryset(self):
    return ScoresRow.objects.order_by('-snpid')[:5]

#uses a generic view 
#expects the url parameter to be a primary key called 'pk'
class DetailView(generic.DetailView):
  model = ScoresRow
  template_name = 'snpSearchTool/detail.html'
  context_variable_name = 'snp_scores_row'


#renders some conrtrols that make other requests?
def controlset(request):
  allRows = ScoresRow.objects.all() 
  return render(request, 'snpSearchTool/controlset.html', { 'all_scores_rows' : allRows }   )


#used to handle form input for a lookup
#redirect on successful lookup is apparently the thing to do.
def lookup_one_snp(request ):
   #snp_scores_row = get_object_or_404(ScoresRow, snpid=requested_snpid) 
   snpid_in = request.POST['requested_snpid']
   try:
     looked_up_row = ScoresRow.objects.get(snpid=snpid_in)
     id_to_use = looked_up_row.id
   except (KeyError, ScoresRow.DoesNotExist):
     return HttpResponse("the snp id " + snpid_in + "isn't here")
     #consider redisplying the control form.
   else:
     return HttpResponseRedirect(reverse('snpSearchTool:detail',  args=(id_to_use,)  ))

def results(request, requested_snpid):
  return HttpResponse("going to check out the results when you ask for %s" % requested_snpid) 

"""  
#detail should show the detail about ONE ScoresRow identified by snpid.
def detail(request, id_of_scoresrow):  #requested_snpid comes out of the url.
  try:
    snp_scores_row = ScoresRow.objects.get(id= id_of_scoresrow)
  except (KeyError, ScoresRow.DoesNotExist):
    raise Http404("Scores row for requested snpid does not exist")
  return render(request, 'snpSearchTool/detail.html', 
            { 'id_of_scoresrow' : id_of_scoresrow,
             'snp_scores_row' : snp_scores_row,
             'more_context'   : "More Context!", })
            #return HttpResponse("detail for snpid: %s" % requested_snpid)
"""

"""
def index(request):
  snp_list = ScoresRow.objects.order_by('-snpid')[:5]
  output = ', '.join(s.snpid for s in snp_list)
  context = { 'snp_list' : snp_list, 'output_str' : output  }
  return render(request, 'snpSearchTool/index.html', context)

"""

atSNPsearch/snpSearchTool/templates/snpSearchTool/controlset.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'snpSearchTool/style.css' %}" />
<div id="background-image"></div>

<h1>This area is for form controls </h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'snpSearchTool:lookup_one_snp' %}" method="post">
{% csrf_token %}
{{ all_scores_rows }}

<input type="radio" name="choice" id="choice1" value="choice1-apples" /> 
<label for="choice1"> choice1 label! APPLES</label> <br/>

<input type="radio" name="choice" id="choice2" value="choice2-oranges" />
<label for="choice2"> choice2 label! ORANGES!</label> <br/>


<input type="text" value="rs99999999" name="requested_snpid" />
<input type="submit" value="Lookup One Snp" />
</form>

atSNPsearch/snpSearchTool/templates/snpSearchTool/detail.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'snpSearchTool/style.css' %}" />
<div id="background-image-detail"></div>
<h1> detail view for one ScoresRow </h1>
<h2> id of selectecd scoresrow: {{ id_of_scoresrow }} </h2>
<h2> self.object:{{ object.snpid }} </h2>
<table>
	<tr> <td> snpid </td>   <td> {{ object.snpid }} </td> </tr>
	<tr> <td> motif </td>   <td> {{ object.motif }} </td> </tr>
	<tr> <td> motif_len</td>   <td> {{ object.motif_len }} </td> </tr>
	<tr> <td>log_lik_ref</td>   <td> {{ object.log_lik_ref }} </td> </tr>
	<tr> <td>log_lik_snp  </td>   <td> {{object.log_lik_snp }} </td> </tr>
	<tr> <td>log_lik_ratio</td>   <td> {{object.log_lik_ratio}} </td> </tr>
	<tr> <td>log_enhance_odds</td>   <td> {{object.log_enhance_odds}} </td> </tr>
	<tr> <td>log_reduce_odds</td>   <td> {{object.log_reduce_odds}} </td> </tr>
	<tr> <td>ref_start</td>   <td> {{object.ref_start}} </td> </tr>
	<tr> <td>snp_start</td>   <td> {{object.snp_start}} </td> </tr>
	<tr> <td>ref_end</td>   <td> {{object.ref_end}} </td> </tr>
	<tr> <td>snp_end</td>   <td> {{object.snp_end}} </td> </tr>
	<tr> <td>ref_strand</td>   <td> {{object.ref_strand}} </td> </tr>
	<tr> <td>snp_strand</td>   <td> {{object.snp_strand}} </td> </tr>
</table>
<a href="{% url 'snpSearchTool:controlset' %}">Back to Lookup </a>

atSNPsearch/snpSearchTool/templates/snpSearchTool/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'snpSearchTool/style.css' %}" />
<div id="background-image"></div>
<h1> hi there! </h1>
{% if snp_list %}
  <ul>
    {% for onesnp in snp_list %}
      <li><a href="{% url 'snpSearchTool:results' onesnp.id %}">
       {{ onesnp.snpid }} one change.. 
          </a>
     </li>
    {%  endfor  %}
  </ul>
 {% else %}
   <p> No snps to show in the index view. </p>
 {% endif %}